export const siteConfig = {
  name: "AQS Technologies",
  legalName: "AQS Technologies",
  tagline: "Your Trusted Technology Supplier & Distributor",
  description:
    "An independent supplier and distributor, sourcing, importing, exporting, and distributing quality technology products across the UAE and region.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://aqstechnologies.com",
  contact: {
    location: "Dubai, UAE",
    whatsappPhone: "+971 56 223 4115",
    phone: "+971 50 496 6409",
    phoneHref: "tel:+971504966409",
    emails: ["abbas@aqsinternational.com", "quresh@aqsinternational.com"],
    emailHref: "mailto:abbas@aqsinternational.com,quresh@aqsinternational.com",
    linkedin: "https://www.linkedin.com/",
    whatsapp: "https://wa.me/971562234115",
    whatsappSecondary: "https://wa.me/971504966409",
  },
  nav: [
    { href: "/", label: "Home" },
    { href: "/about", label: "About Us" },
    { href: "/products", label: "Products", menu: "products" },
    { href: "/partners", label: "Partners", menu: "partners" },
    { href: "/blogs", label: "Blogs" },
    { href: "/contact", label: "Contact Us" },
  ],
  heroHighlights: [
    { title: "Genuine Products" },
    { title: "Reliable Supply" },
    { title: "Expert Consultation" },
    { title: "Competitive Pricing" },
  ],
  productCategories: [
    {
      title: "Access Control",
      slug: "access-control",
      href: "/products/access-control",
      image: "/images/category-access-control-hid.png",
      blurb:
        "HID readers, Aero controllers, iCLASS and Vento cards, door locks, emergency break glass, and iSecure software.",
      aboutBlurb:
        "Reliable access control, identity and security solutions for modern workplaces.",
      links: [
        {
          label: "HID Signo Readers",
          slug: "readers",
          href: "/products/access-control/readers",
          image: "/images/product-readers.png",
          spec: "HID Signo 40 RFID / mobile",        },
        {
          label: "HID Readers",
          slug: "hid-readers",
          href: "/products/access-control/hid-readers",
          image: "/images/product-hid-readers.png",
          spec: "HID iCLASS SE R40 & RK40 readers",        },
        {
          label: "HID Seos Cards & Credentials",
          slug: "access-cards",
          href: "/products/access-control/access-cards",
          image: "/images/product-seos-cards.png",
          spec: "Seos smart cards and credentials",        },
        {
          label: "HID Amico Readers",
          slug: "door-accessories",
          href: "/products/access-control/door-accessories",
          image: "/images/product-door.png",
          spec: "HID Amico biometric face readers",        },
        {
          label: "HID Aero Controller",
          slug: "hid-aero",
          href: "/products/access-control/hid-aero",
          image: "/images/product-hid-aero.png",
          spec: "HID Aero X1100 access controller",        },
        {
          label: "HID iCLASS",
          slug: "hid-iclass",
          href: "/products/access-control/hid-iclass",
          image: "/images/product-hid-iclass-cards.png",
          spec: "HID iCLASS cards and credentials",        },
        {
          label: "HID Vento Card",
          slug: "hid-vento-card",
          href: "/products/access-control/hid-vento-card",
          image: "/images/product-hid-vento-card.png",
          spec: "HID Vento access cards",        },
        {
          label: "Door Locks",
          slug: "door-locks",
          href: "/products/access-control/door-locks",
          image: "/images/product-door-locks.png",
          spec: "Electromagnetic door locks",        },
        {
          label: "Emergency Break Glass",
          slug: "emergency-break-glass",
          href: "/products/access-control/emergency-break-glass",
          image: "/images/product-emergency-break-glass.png",
          spec: "Emergency door release break glass",        },
        {
          label: "iSecure IAM",
          slug: "isecure-iam",
          href: "/products/access-control/isecure-iam",
          image: "/images/product-isecure-iam.png",
          spec: "Enterprise identity & access management",        },
        {
          label: "iSecure Trace",
          slug: "isecure-trace",
          href: "/products/access-control/isecure-trace",
          image: "/images/product-isecure-trace.png",
          spec: "Visitor management",        },
        {
          label: "iSecure Cafe",
          slug: "isecure-cafe",
          href: "/products/access-control/isecure-cafe",
          image: "/images/product-isecure-cafe.png",
          spec: "Cafeteria management",        },
        {
          label: "iSecure Mobile",
          slug: "isecure-mobile",
          href: "/products/access-control/isecure-mobile",
          image: "/images/product-isecure-mobile.png",
          spec: "Mobile identity & attendance",        },
        {
          label: "iSecure Identity",
          slug: "isecure-identity",
          href: "/products/access-control/isecure-identity",
          image: "/images/product-isecure-identity.png",
          spec: "Identity analytics & alerts",        },
        {
          label: "iSecure HRMS",
          slug: "isecure-hrms",
          href: "/products/access-control/isecure-hrms",
          image: "/images/product-isecure-hrms.png",
          spec: "Time, attendance & HRMS integration",        },
      ],
    },
    {
      title: "Audio Video",
      slug: "audio-video",
      href: "/products/audio-video",
      image: "/images/product-interactive-flat-screen-5.jpg",
      blurb:
        "TREND by STEPWELL interactive displays, conferencing, adapters, converters, mixers and splitters.",
      aboutBlurb: "TREND by STEPWELL audio video solutions.",
      links: [
        {
          label: "Video Conferencing Display",
          slug: "video-conferencing-display",
          href: "/products/audio-video/video-conferencing-display",
          image: "/images/product-video-conferencing-display.jpg",
          spec: "TREND flat panel with video bar for meeting rooms",
        },
        {
          label: "Video Wall",
          slug: "video-wall",
          href: "/products/audio-video/video-wall",
          image: "/images/product-interactive-flat-screen-2.jpg",
          spec: "TREND large-format video wall",
        },
        {
          label: "Plug & Play Conference Camera",
          slug: "plug-play-conference-camera",
          href: "/products/audio-video/plug-play-conference-camera",
          image: "/images/product-interactive-flat-screen-3.jpg",
          spec: "TREND USB conference camera bar",
        },
        {
          label: "Wireless Screen Sharing",
          slug: "wireless-screen-sharing",
          href: "/products/audio-video/wireless-screen-sharing",
          image: "/images/product-interactive-flat-screen-5.jpg",
          spec: "TREND interactive flat screen with wireless casting",
        },
        {
          label: "Interactive Flat Panel",
          slug: "interactive-flat-panel",
          href: "/products/audio-video/interactive-flat-panel",
          image: "/images/product-interactive-flat-panel.png",
          spec: "TREND interactive flat panel D Series",
        },
        {
          label: "Lecture Recording System",
          slug: "lecture-recording-system",
          href: "/products/audio-video/lecture-recording-system",
          image: "/images/product-lecture-recording-system.png",
          spec: "TREND lecture archiving system",
        },
        {
          label: "Adapters",
          slug: "adapters",
          href: "/products/audio-video/adapters",
          image: "/images/product-adapters.jpg",
          spec: "TREND by STEPWELL Type-C, HDMI and USB adapters",
        },
        {
          label: "Converters",
          slug: "converters",
          href: "/products/audio-video/converters",
          image: "/images/product-converters.png",
          spec: "TREND by STEPWELL HDMI and wireless converters",
        },
        {
          label: "Mixers",
          slug: "mixers",
          href: "/products/audio-video/mixers",
          image: "/images/product-mixers.jpg",
          spec: "TREND by STEPWELL conference audio",
        },
        {
          label: "Splitters",
          slug: "splitters",
          href: "/products/audio-video/splitters",
          image: "/images/product-splitters.png",
          spec: "TREND by STEPWELL multi-screen splitters",
        },
      ],
    },
    {
      title: "Networking",
      slug: "networking",
      href: "/products/networking",
      image: "/images/category-networking-cables.png",
      blurb:
        "LAN, BMS, HDMI, telecommunication, copper and fiber optic cables, plus LAN, copper and optical fiber accessories.",
      aboutBlurb: "Network cabling, connectivity and LAN accessories.",
      links: [
        {
          label: "LAN Cables",
          slug: "lan-cables",
          href: "/products/networking/lan-cables",
          image: "/images/product-lan-cables.png",
          spec: "KAYBE network cable boxes",
        },
        {
          label: "BMS Cables",
          slug: "bms-cables",
          href: "/products/networking/bms-cables",
          image: "/images/product-bms-cables.png",
          spec: "KAYBE 100% copper cable reels",
        },
        {
          label: "LAN Accessories",
          slug: "lan-accessories",
          href: "/products/networking/lan-accessories",
          image: "/images/product-lan-accessories.png",
          spec: "Patch panels, keystones & connectors",
        },
        {
          label: "HDMI Cables",
          slug: "hdmi-cables",
          href: "/products/networking/hdmi-cables",
          image: "/images/product-hdmi-cables.png",
          spec: "KAYBE 4K HDMI cables",
        },
        {
          label: "Fiber Optical Cables",
          slug: "fiber-optic-cables",
          href: "/products/networking/fiber-optic-cables",
          image: "/images/product-fiber-optic-cables.png",
          spec: "Indoor & outdoor fiber cables",
        },
        {
          label: "Telecommunication Cables",
          slug: "telecommunication-cables",
          href: "/products/networking/telecommunication-cables",
          image: "/images/product-telecommunication-cables.png",
          spec: "Multi-pair telephone and telecom cables",
        },
      ],
    },
    {
      title: "Networking & Racks",
      slug: "enclosures",
      href: "/products/enclosures",
      image: "/images/category-enclosures.png",
      blurb: "Server racks, networking cabinets, open frames and specialized racks.",
      aboutBlurb: "Server racks, networking cabinets and specialised racks.",
      links: [
        {
          label: "Server Racks",
          slug: "server-racks",
          href: "/products/enclosures/server-racks",
          image: "/images/product-server-rack.jpg",
          spec: "Floor-standing cabinets",
        },
        {
          label: "Networking Racks",
          slug: "networking-racks",
          href: "/products/enclosures/networking-racks",
          image: "/images/product-network-rack.jpg",
          spec: "Data & AV cabinets",
        },
        {
          label: "Open Frame Racks",
          slug: "open-frame-racks",
          href: "/products/enclosures/open-frame-racks",
          image: "/images/product-open-rack.jpg",
          spec: "2-post & 4-post frames",
        },
        {
          label: "Specialized Racks",
          slug: "specialized-racks",
          href: "/products/enclosures/specialized-racks",
          image: "/images/product-special-rack.png",
          spec: "Wall-mount cabinets",
        },
      ],
    },
  ],
  partners: [
    {
      name: "HID",
      slug: "hid",
      description: "Access control and identity products.",
      aboutLine: "Access Control Products",
      href: "/products?brand=hid",
      logo: "/brands/hid-logo.png",
      categorySlugs: ["access-control"],
    },
    {
      name: "Security Shells Infotech",
      slug: "security-shells",
      description: "Enterprise Security and Identity Management.",
      aboutLine: "Security Shells Infotech",
      href: "/products?brand=security-shells",
      logo: "/brands/security-shells.png",
      categorySlugs: ["access-control"],
    },
    {
      name: "TREND",
      slug: "trend",
      description: "Audio Video (AV) solutions.",
      aboutLine: "TREND by STEPWELL",
      href: "/products?brand=trend",
      logo: "/brands/trend.png",
      categorySlugs: ["audio-video"],
    },
    {
      name: "KAYBE",
      slug: "kaybe",
      description: "Networking & Enclosure Solutions.",
      aboutLine: "Networking & Enclosure Solutions",
      href: "/products?brand=kaybe",
      logo: "/brands/kaybe.png",
      categorySlugs: ["networking", "enclosures"],
    },
  ],
  whyChoose: [
    {
      title: "Genuine Products",
      text: "We supply authentic products from leading technology brands.",
    },
    {
      title: "Reliable Supply",
      text: "Consistent stock and delivery support for workplace projects.",
    },
    {
      title: "Competitive Pricing",
      text: "Clear quotes that fit your specification and budget.",
    },
    {
      title: "Responsive Service",
      text: "A team that helps you specify, source, and follow through.",
    },
  ],
  blogs: [
    {
      title: "How Interactive Displays Are Transforming Modern Workplaces",
      href: "/blogs",
      image: "/images/blog-displays.jpg",
      date: "Oct 2026",
    },
    {
      title: "A Guide to Choosing the Right Access Control System",
      href: "/blogs",
      image: "/images/blog-access.jpg",
      date: "Oct 2026",
    },
    {
      title: "Understanding Different Types of Network Cables and Their Applications",
      href: "/blogs",
      image: "/images/blog-cables.jpg",
      date: "Sep 2026",
    },
  ],
  footer: {
    blurb:
      "AQS Technologies is an independent technology supplier and distributor serving workplaces across the UAE and region.",
    quickLinks: [
      { href: "/", label: "Home" },
      { href: "/about", label: "About Us" },
      { href: "/products", label: "Products" },
      { href: "/partners", label: "Partners" },
      { href: "/contact", label: "Contact Us" },
    ],
  },
  about: {
    eyebrow: "About Us",
    intro:
      "Founded in 2022, AQS Technologies is a sister concern of AQS International Trading LLC, a dynamic and diversified independant distribution and supply company based in Dubai, UAE. With a strong commitment to excellence, we specialize in sourcing, importing, exporting, and distributing a wide range of high-quality products across various industries, including - Data & Communication Cables, Control Cables, LED Screens and AV Accessories, Access Control Readers, Controllers, Cards, Hard drives and more.",
    story:
      "Over the years, we’ve built strong partnerships with manufacturers, suppliers, and system partners around the region, ensuring that our customers receive top-tier products at competitive prices.",
    stats: [
      { value: "2022", label: "Year Established" },
      { value: "50+", label: "Projects Supplied" },
      { value: "20+", label: "Partner Brands" },
      { value: "100%", label: "Quality Focused" },
    ],
    highlights: [
      "Data & Communication Cables",
      "Control Cables",
      "LED Screens and AV Accessories",
      "Access Control Readers, Controllers, Cards",
      "Hard drives and more",
    ],
    vision:
      "To become a trusted regional distributor in advanced technology infrastructure, AV and smart security products.",
    mission:
      "To deliver innovative, reliable, and high performance technology products through strategic partnerships and customer centric approach.",
    categoryEyebrow: "Our Business Areas",
    categoryIntro:
      "We supply a complete range of technology products to meet the needs of modern businesses. From secure access to collaboration to reliable networking infrastructure.",
    brandsEyebrow: "Our Technology Partners",
    brandsTitle: "Global Brands We Work With",
    brandsIntro:
      "We supply and distribute genuine technology products from trusted global brands.",
    whyTitle: "Why Choose Us?",
    why: [
      {
        title: "Diverse Product Range",
        text: "From everyday Networking, Security and AV goods to specialized & hybrid products, we meet a broad spectrum of supply needs.",
      },
      {
        title: "Global Network",
        text: "Our international partnerships allow us to operate efficiently across borders and deliver on-time products regionally.",
      },
      {
        title: "Customer-Centric Approach",
        text: "We believe in building long-term relationships through transparency, trust, and responsive service.",
      },
      {
        title: "Quality & Compliance",
        text: "We adhere to international standards to ensure that every product meets quality and regulatory benchmarks.",
      },
    ],
    processEyebrow: "Our Process",
    processTitle: "How We Support Your Business",
    processIntro:
      "From product selection to delivery, we ensure a smooth and reliable experience.",
    process: [
      { title: "Requirement Understanding", text: "We listen first" },
      { title: "Product Selection", text: "The Right Products" },
      { title: "Competitive Pricing", text: "Quality Competitive Pricing" },
      { title: "Quality Assurance", text: "Genuine products you can trust" },
      { title: "Timely Delivery", text: "Reliable supply on schedule" },
      { title: "Ongoing Support", text: "Help after the sale" },
    ],
    regionTitle: "Serving UAE and the Region",
    regionText:
      "Based in Dubai, we supply technology products to businesses across the UAE and international markets through our trusted partners.",
    regionStats: [
      { value: "Dubai, UAE", label: "Head Office" },
      { value: "GCC", label: "Countries Served" },
      { value: "50+", label: "Projects" },
    ],
    ctaTitle: "Let's Build a Smarter, More Connected Workplace",
    ctaText:
      "Get in touch with our team for product availability, pricing and expert guidance.",
  },
  services: [
    {
      title: "Websites",
      description: "Fast, accessible marketing sites and web applications.",
    },
    {
      title: "Software",
      description: "Custom tools that fit how your team already works.",
    },
    {
      title: "Digital products",
      description: "Product design, build, and launch support.",
    },
  ],
} as const;
